/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazilimmaliyettespiti;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Mert-PC
 */
public class AnaPencere extends javax.swing.JFrame {

    /**
     * Creates new form AnaPencere
     */
    private Timer t;
    private Timer t2;
    private ActionListener a1;
    private ActionListener a2;
    
    public AnaPencere() {
        initComponents();
        a1 = new ActionListener(){
            

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                if(progressbar1.getValue() < 100){
                progressbar1.setValue(progressbar1.getValue()+5);
                }else {
                    t.stop();
                }
                
            }
        };
        
            t = new Timer(8,a1);
        a2 = new ActionListener(){
            

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                
                if(progressbar3.getValue() < 100){
                progressbar3.setValue(progressbar3.getValue()+5);
                }else {
                    t.stop();
                }
            }
        };
        t2 = new Timer(8,a2);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        basic1radio = new javax.swing.JRadioButton();
        basic2radio = new javax.swing.JRadioButton();
        basic3radio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        basitkodsayisi = new javax.swing.JTextField();
        basitefor = new javax.swing.JTextField();
        basitverimlilik = new javax.swing.JTextField();
        basitzaman = new javax.swing.JTextField();
        basitkisisayisi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        progressbar1 = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        orta1radio = new javax.swing.JRadioButton();
        orta2radio = new javax.swing.JRadioButton();
        orta3radio = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        ortakodsayisi = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ortaslider = new javax.swing.JSlider();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ortaefor = new javax.swing.JTextField();
        ortazaman = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ortaverimlilik = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        ortakisisayisi = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        progressbar3 = new javax.swing.JProgressBar();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        basic1radio2 = new javax.swing.JRadioButton();
        jLabel43 = new javax.swing.JLabel();
        basic2radio2 = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        basic3radio2 = new javax.swing.JRadioButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        basitkodsayisi2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        slider3 = new javax.swing.JSlider();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        basitefor2 = new javax.swing.JTextField();
        basitzaman2 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        basitverimlilik2 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        basitkisisayisi2 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        progressbar4 = new javax.swing.JProgressBar();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();

        buttonGroup1.add(basic1radio);
        buttonGroup1.add(basic2radio);
        buttonGroup1.add(basic3radio);

        buttonGroup2.add(orta1radio);
        buttonGroup2.add(orta2radio);
        buttonGroup2.add(orta3radio);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YAZILIM MALİYET TESPİTİ");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/son.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 644, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTabbedPane2.setRequestFocusEnabled(false);

        jPanel4.setForeground(new java.awt.Color(0, 159, 239));
        jPanel4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        basic1radio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        basic1radio.setSelected(true);
        basic1radio.setText("Organik Mod");
        basic1radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic1radioActionPerformed(evt);
            }
        });

        basic2radio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        basic2radio.setText("Yarı Özel Mod");
        basic2radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic2radioActionPerformed(evt);
            }
        });

        basic3radio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        basic3radio.setText("Gömülü Mod");
        basic3radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic3radioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mod Seçiniz");

        basitkodsayisi.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        basitkodsayisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basitkodsayisiActionPerformed(evt);
            }
        });

        basitefor.setEditable(false);
        basitefor.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        basitverimlilik.setEditable(false);
        basitverimlilik.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        basitzaman.setEditable(false);
        basitzaman.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        basitzaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basitzamanActionPerformed(evt);
            }
        });

        basitkisisayisi.setEditable(false);
        basitkisisayisi.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Kod Satır Sayısınız Giriniz");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hesaplanan Efor");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Verimlilik");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Geliştirme İçin Gereken Zaman");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Ortalama Kişi İhtiyacı");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/puzzle.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flow-chart.png"))); // NOI18N

        slider1.setMajorTickSpacing(10000);
        slider1.setMaximum(10000000);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stopwatch.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rgb.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network (1).png"))); // NOI18N

        progressbar1.setBackground(new java.awt.Color(51, 51, 255));
        progressbar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        progressbar1.setStringPainted(true);
        progressbar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                progressbar1MousePressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, progressbar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel4Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(slider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 351, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                                    .add(basic1radio)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(81, 81, 81)
                                    .add(basic2radio)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jPanel4Layout.createSequentialGroup()
                                    .add(basitkodsayisi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(85, 85, 85)
                                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jLabel2)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(basitverimlilik, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel4Layout.createSequentialGroup()
                                        .add(jLabel4)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel4Layout.createSequentialGroup()
                                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                                                .add(jLabel3)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, basitefor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(92, 92, 92)
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel4Layout.createSequentialGroup()
                                        .add(jLabel6)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jLabel5)
                                    .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(basitzaman)
                                        .add(basitkisisayisi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))))
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                                .add(basic3radio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(49, 49, 49))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(jLabel22)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(basic2radio)
                        .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(basic3radio)
                            .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(basic1radio))
                .add(18, 18, 18)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(basitkodsayisi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1))
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(slider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 50, Short.MAX_VALUE)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel3)
                                .add(jLabel5)
                                .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(32, 32, 32)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(basitefor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(basitzaman, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel4)
                                .add(jLabel6))
                            .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(177, 177, 177)
                        .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(basitverimlilik, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(basitkisisayisi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(progressbar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Basit Cocomo ", new javax.swing.ImageIcon(getClass().getResource("/images/budget (8).png")), jPanel4); // NOI18N

        orta1radio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orta1radio.setSelected(true);
        orta1radio.setText("Organik Mod");
        orta1radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orta1radioActionPerformed(evt);
            }
        });

        orta2radio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orta2radio.setText("Yarı Özel Mod");
        orta2radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orta2radioActionPerformed(evt);
            }
        });

        orta3radio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orta3radio.setText("Gömülü Mod");
        orta3radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orta3radioActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins.png"))); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/puzzle.png"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flow-chart.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Kod Satır Sayısınız Giriniz");

        ortakodsayisi.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        ortakodsayisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ortakodsayisiActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        jButton3.setText("Hesapla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ortaslider.setMajorTickSpacing(10000);
        ortaslider.setMaximum(10000000);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Hesaplanan Efor");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Geliştirme İçin Gereken Zaman");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stopwatch.png"))); // NOI18N

        ortaefor.setEditable(false);
        ortaefor.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        ortazaman.setEditable(false);
        ortazaman.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        ortazaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ortazamanActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Verimlilik");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rgb.png"))); // NOI18N

        ortaverimlilik.setEditable(false);
        ortaverimlilik.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("Ortalama Kişi İhtiyacı");

        ortakisisayisi.setEditable(false);
        ortakisisayisi.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network (1).png"))); // NOI18N

        progressbar3.setBackground(new java.awt.Color(51, 51, 255));
        progressbar3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        progressbar3.setStringPainted(true);
        progressbar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                progressbar3MousePressed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("Mod Seçiniz");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, progressbar3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel5Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel41)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(ortaslider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 351, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5Layout.createSequentialGroup()
                                    .add(orta1radio)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(81, 81, 81)
                                    .add(orta2radio)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(jLabel30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jPanel5Layout.createSequentialGroup()
                                    .add(ortakodsayisi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(85, 85, 85)
                                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jLabel32)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ortaverimlilik, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel5Layout.createSequentialGroup()
                                        .add(jLabel37)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel5Layout.createSequentialGroup()
                                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5Layout.createSequentialGroup()
                                                .add(jLabel33)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, ortaefor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(92, 92, 92)
                                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel5Layout.createSequentialGroup()
                                        .add(jLabel39)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jLabel35)
                                    .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(ortazaman)
                                        .add(ortakisisayisi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))))
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                                .add(orta3radio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(49, 49, 49))
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(jLabel36)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel41)
                .add(18, 18, 18)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel29, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(orta2radio)
                        .add(jLabel30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(orta3radio)
                            .add(jLabel31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(orta1radio))
                .add(18, 18, 18)
                .add(jLabel32)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(ortakodsayisi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3))
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(ortaslider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 50, Short.MAX_VALUE)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel33)
                                .add(jLabel35)
                                .add(jLabel42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(32, 32, 32)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ortaefor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ortazaman, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel37)
                                .add(jLabel39))
                            .add(jLabel38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(177, 177, 177)
                        .add(jLabel40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ortaverimlilik, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ortakisisayisi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(progressbar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Orta Düzey Cocomo", new javax.swing.ImageIcon(getClass().getResource("/images/budget (9).png")), jPanel5); // NOI18N

        basic1radio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        basic1radio2.setSelected(true);
        basic1radio2.setText("Organik Mod");
        basic1radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic1radio2ActionPerformed(evt);
            }
        });

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins.png"))); // NOI18N

        basic2radio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        basic2radio2.setText("Yarı Özel Mod");
        basic2radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic2radio2ActionPerformed(evt);
            }
        });

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/puzzle.png"))); // NOI18N

        basic3radio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        basic3radio2.setText("Gömülü Mod");
        basic3radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic3radio2ActionPerformed(evt);
            }
        });

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flow-chart.png"))); // NOI18N

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setText("Kod Satır Sayısınız Giriniz");

        basitkodsayisi2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        basitkodsayisi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basitkodsayisi2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        jButton4.setText("Hesapla");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        slider3.setMajorTickSpacing(10000);
        slider3.setMaximum(10000000);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setText("Hesaplanan Efor");

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network.png"))); // NOI18N

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Geliştirme İçin Gereken Zaman");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stopwatch.png"))); // NOI18N

        basitefor2.setEditable(false);
        basitefor2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        basitzaman2.setEditable(false);
        basitzaman2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        basitzaman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basitzaman2ActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setText("Verimlilik");

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rgb.png"))); // NOI18N

        basitverimlilik2.setEditable(false);
        basitverimlilik2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel53.setText("Ortalama Kişi İhtiyacı");

        basitkisisayisi2.setEditable(false);
        basitkisisayisi2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network (1).png"))); // NOI18N

        progressbar4.setBackground(new java.awt.Color(51, 51, 255));
        progressbar4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        progressbar4.setStringPainted(true);
        progressbar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                progressbar4MousePressed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("Mod Seçiniz");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, progressbar4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel6Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jLabel55)
                        .add(0, 551, Short.MAX_VALUE))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(slider3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 351, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel6Layout.createSequentialGroup()
                                    .add(basic1radio2)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(81, 81, 81)
                                    .add(basic2radio2)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(jLabel44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jPanel6Layout.createSequentialGroup()
                                    .add(basitkodsayisi2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(85, 85, 85)
                                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jLabel46)
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(basitverimlilik2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel6Layout.createSequentialGroup()
                                        .add(jLabel51)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel6Layout.createSequentialGroup()
                                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel6Layout.createSequentialGroup()
                                                .add(jLabel47)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, basitefor2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(92, 92, 92)
                                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel6Layout.createSequentialGroup()
                                        .add(jLabel53)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jLabel49)
                                    .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(basitzaman2)
                                        .add(basitkisisayisi2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))))
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                                .add(basic3radio2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(49, 49, 49))
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(jLabel50)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel55)
                .add(18, 18, 18)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel43, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(basic2radio2)
                        .add(jLabel44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(basic3radio2)
                            .add(jLabel45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(basic1radio2))
                .add(18, 18, 18)
                .add(jLabel46)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(basitkodsayisi2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4))
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(slider3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 50, Short.MAX_VALUE)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel47)
                                .add(jLabel49)
                                .add(jLabel56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(32, 32, 32)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(basitefor2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(basitzaman2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel51)
                                .add(jLabel53))
                            .add(jLabel52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                        .add(177, 177, 177)
                        .add(jLabel54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(basitverimlilik2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(basitkisisayisi2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(progressbar4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Detaylı Cocomo", new javax.swing.ImageIcon(getClass().getResource("/images/hourglass.png")), jPanel6); // NOI18N

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, -1, -1));
        jTabbedPane2.getAccessibleContext().setAccessibleName("Detaylı Cocomo");
        jTabbedPane2.getAccessibleContext().setAccessibleDescription("Detaylı Cocomo Modeline Göre Hesaplama Yapar");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void basic1radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic1radioActionPerformed
                    // TODO add your handling code here:
        
    }//GEN-LAST:event_basic1radioActionPerformed

    private void basic3radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic3radioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_basic3radioActionPerformed

    private void basitkodsayisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basitkodsayisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basitkodsayisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    // TODO add your handling code here:
                    
                    t.start();
                    progressbar1.setValue(0);
     
                    if(basic1radio.isSelected()){
                        int kodsatirsayisi = Integer.parseInt(basitkodsayisi.getText());
                        double efor = 2.4*(Math.pow((kodsatirsayisi/1000),1.04));
                        basitefor.setText(Double.toString(efor));
                        double sure = 2.5*(Math.pow((kodsatirsayisi/1000),0.38));
                        basitzaman.setText(Double.toString(sure));
                        double calisansayisi = (efor/sure);
                        basitkisisayisi.setText(Double.toString(calisansayisi));
                        double verimlilik = kodsatirsayisi/efor;
                        basitverimlilik.setText(Double.toString(verimlilik)); 
                        if(kodsatirsayisi >= 10000000){
                            kodsatirsayisi = 10000000;
                            slider1.setValue(kodsatirsayisi);
                        }else{
                            slider1.setValue(kodsatirsayisi);
                        }
                    }
                    if(basic2radio.isSelected()){
                        int kodsatirsayisi = Integer.parseInt(basitkodsayisi.getText());
                        double efor = 3*(Math.pow((kodsatirsayisi/1000),1.12));
                        basitefor.setText(Double.toString(efor));
                        double sure = 2.5*(Math.pow((kodsatirsayisi/1000),0.35));
                        basitzaman.setText(Double.toString(sure));
                        double calisansayisi = (efor/sure);
                        basitkisisayisi.setText(Double.toString(calisansayisi));
                        double verimlilik = kodsatirsayisi/efor;
                        basitverimlilik.setText(Double.toString(verimlilik));
                        if(kodsatirsayisi >= 10000000){
                            kodsatirsayisi = 10000000;
                            slider1.setValue(kodsatirsayisi);
                        }else{
                            slider1.setValue(kodsatirsayisi);
                        }
                    }
                    if(basic3radio.isSelected()){
                    int kodsatirsayisi = Integer.parseInt(basitkodsayisi.getText());
                    double efor = 3.6*(Math.pow((kodsatirsayisi/1000),1.2));
                    basitefor.setText(Double.toString(efor));
                    double sure = 2.5*(Math.pow((kodsatirsayisi/1000),0.32));
                    basitzaman.setText(Double.toString(sure));
                    double calisansayisi = (efor/sure);
                    basitkisisayisi.setText(Double.toString(calisansayisi));
                    double verimlilik = kodsatirsayisi/efor;
                    basitverimlilik.setText(Double.toString(verimlilik));
                     if(kodsatirsayisi >= 10000000){
                        kodsatirsayisi = 10000000;
                    slider1.setValue(kodsatirsayisi);
                    }else{
                    slider1.setValue(kodsatirsayisi);
                    }
                    
                    }
                                 
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void basic2radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic2radioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_basic2radioActionPerformed

    private void basitzamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basitzamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basitzamanActionPerformed

    private void progressbar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressbar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_progressbar1MousePressed

    private void orta1radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orta1radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orta1radioActionPerformed

    private void orta2radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orta2radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orta2radioActionPerformed

    private void orta3radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orta3radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orta3radioActionPerformed

    private void ortakodsayisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ortakodsayisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ortakodsayisiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                    t.start();
                    progressbar3.setValue(0);
                  
                    if(orta1radio.isSelected()){
                    int kodsatirsayisi = Integer.parseInt(ortakodsayisi.getText());
                    double efor = 2.4*(Math.pow((kodsatirsayisi/1000),1.04));
                    ortaefor.setText(Double.toString(efor));
                    double sure = 2.5*(Math.pow((kodsatirsayisi/1000),0.38));
                    ortazaman.setText(Double.toString(sure));
                    double calisansayisi = (efor/sure);
                    ortakisisayisi.setText(Double.toString(calisansayisi));
                    double verimlilik = kodsatirsayisi/efor;
                    ortaverimlilik.setText(Double.toString(verimlilik)); 
                    if(kodsatirsayisi >= 10000000){
                        kodsatirsayisi = 10000000;
                    ortaslider.setValue(kodsatirsayisi);
                    }else{
                    ortaslider.setValue(kodsatirsayisi);
                    }
                    }
                    if(orta2radio.isSelected()){
                    int kodsatirsayisi = Integer.parseInt(ortakodsayisi.getText());
                    double efor = 3*(Math.pow((kodsatirsayisi/1000),1.12));
                    ortaefor.setText(Double.toString(efor));
                    double sure = 2.5*(Math.pow((kodsatirsayisi/1000),0.35));
                    ortazaman.setText(Double.toString(sure));
                    double calisansayisi = (efor/sure);
                    ortakisisayisi.setText(Double.toString(calisansayisi));
                    double verimlilik = kodsatirsayisi/efor;
                    ortaverimlilik.setText(Double.toString(verimlilik));
                    if(kodsatirsayisi >= 10000000){
                        kodsatirsayisi = 10000000;
                    ortaslider.setValue(kodsatirsayisi);
                    }else{
                    ortaslider.setValue(kodsatirsayisi);
                    }
                    }
                    if(orta3radio.isSelected()){
                    int kodsatirsayisi = Integer.parseInt(ortakodsayisi.getText());
                    double efor = 3.6*(Math.pow((kodsatirsayisi/1000),1.2));
                    ortaefor.setText(Double.toString(efor));
                    double sure = 2.5*(Math.pow((kodsatirsayisi/1000),0.32));
                    ortazaman.setText(Double.toString(sure));
                    double calisansayisi = (efor/sure);
                    ortakisisayisi.setText(Double.toString(calisansayisi));
                    double verimlilik = kodsatirsayisi/efor;
                    ortaverimlilik.setText(Double.toString(verimlilik));
                     if(kodsatirsayisi >= 10000000){
                        kodsatirsayisi = 10000000;
                    ortaslider.setValue(kodsatirsayisi);
                    }else{
                    ortaslider.setValue(kodsatirsayisi);
                    }
                    
                    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ortazamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ortazamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ortazamanActionPerformed

    private void progressbar3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressbar3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_progressbar3MousePressed

    private void basic1radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic1radio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basic1radio2ActionPerformed

    private void basic2radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic2radio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basic2radio2ActionPerformed

    private void basic3radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic3radio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basic3radio2ActionPerformed

    private void basitkodsayisi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basitkodsayisi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basitkodsayisi2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void basitzaman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basitzaman2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basitzaman2ActionPerformed

    private void progressbar4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressbar4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_progressbar4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
            

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaPencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JRadioButton basic1radio;
    private static javax.swing.JRadioButton basic1radio2;
    private static javax.swing.JRadioButton basic2radio;
    private static javax.swing.JRadioButton basic2radio2;
    private static javax.swing.JRadioButton basic3radio;
    private static javax.swing.JRadioButton basic3radio2;
    private javax.swing.JTextField basitefor;
    private javax.swing.JTextField basitefor2;
    private javax.swing.JTextField basitkisisayisi;
    private javax.swing.JTextField basitkisisayisi2;
    private javax.swing.JTextField basitkodsayisi;
    private javax.swing.JTextField basitkodsayisi2;
    private javax.swing.JTextField basitverimlilik;
    private javax.swing.JTextField basitverimlilik2;
    private javax.swing.JTextField basitzaman;
    private javax.swing.JTextField basitzaman2;
    private static javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private static javax.swing.JRadioButton orta1radio;
    private static javax.swing.JRadioButton orta2radio;
    private static javax.swing.JRadioButton orta3radio;
    private javax.swing.JTextField ortaefor;
    private javax.swing.JTextField ortakisisayisi;
    private javax.swing.JTextField ortakodsayisi;
    private static javax.swing.JSlider ortaslider;
    private javax.swing.JTextField ortaverimlilik;
    private javax.swing.JTextField ortazaman;
    private static javax.swing.JProgressBar progressbar1;
    private static javax.swing.JProgressBar progressbar3;
    private static javax.swing.JProgressBar progressbar4;
    private static javax.swing.JSlider slider1;
    private static javax.swing.JSlider slider3;
    // End of variables declaration//GEN-END:variables
}
